<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2010-08-25 12:12

$extensionClassesPath = t3lib_extMgm::extPath('extbase_webservices') . 'Classes/';
$libraryClassesPath = t3lib_extMgm::extPath('extbase_webservices') . 'Resources/Library/';
return array(
	'tx_extbasewebservices_helper_wsdl' => $extensionTestsPath . 'BaseTestCase.php',
	'nusoap_server' => $libraryClassesPath . 'NuSoap/class.soap_server.php',
);
?>